### PR TITLE
Fixes #59 handle last header name without quotes

### LINKED ISSUE #59: Unable to parse header on registry
On a certain registry which returns a rel=next without quotes a stack trace is returned.

```
irb(main):012:0> require 'docker_registry2'
=> false

irb(main):013:0> docker = DockerRegistry2.connect('https://registry.opensource.zalan.do')

irb(main):014:0> docker
=> #<DockerRegistry2::Registry:0x0000557fffdeb320 @uri=#<URI::HTTPS https://registry.opensource.zalan.do>, @base_uri="https://registry.opensource.zalan.do:443", @user=nil, @password=nil, @http_options={:open_timeout=>2, :read_timeout=>5}>

irb(main):015:0> docker.tags('acid/logical-backup')
Traceback (most recent call last):
8: from /usr/bin/irb:23:in `<main>'
7: from /usr/bin/irb:23:in `load'
6: from /usr/lib/ruby/gems/2.7.0/gems/irb-1.2.1/exe/irb:11:in `<top (required)>'
5: from (irb):15
4: from /var/lib/gems/2.7.0/gems/docker_registry2-1.10.0/lib/registry/registry.rb:69:in `tags'
3: from /var/lib/gems/2.7.0/gems/docker_registry2-1.10.0/lib/registry/registry.rb:221:in `last'
2: from /var/lib/gems/2.7.0/gems/docker_registry2-1.10.0/lib/registry/registry.rb:221:in `each'
1: from /var/lib/gems/2.7.0/gems/docker_registry2-1.10.0/lib/registry/registry.rb:224:in `block in last'
NoMethodError (undefined method `to_sym' for nil:NilClass)
```

The header appears to be in this form:

```
<https://registry.opensource.zalan.do/v2/acid/logical-backup/tags/list?n=1000&last=v1.7.1-58-gcde88d37>; rel=next
```

Corresponding code regarding this appears to be:
https://github.com/deitch/docker_registry2/blob/220c03d5d2ad0268ca97ecabb16cc8ec58943dbd/lib/registry/registry.rb#L220

### PR DESCRIPTION
**Pull request by liger1978**

### CODE REVIEW

**Comment by liger1978** [comment]
I've opened PR #60 that fixes this.

**Comment by deitch** [comment]
This looks fine to me, and thank you for adding it. Are we sure that it doesn't break anything in other registries? Can we check against images in, say, docker hub and GHCR?

**Review by deitch — APPROVED** [review]

**Comment by liger1978** [comment]
@deitch Hi Avi, any chance of a new gem release?

**Comment by deitch** [comment]
Done

**Pull request merged**
