### PR TITLE
PR #85 introduce a regression for the digest for images without variant

### LINKED ISSUE #88: Wrong digest on artifacts
Hello,

Since the last update, the gem does't find the right digest on my harbor registry.
The images are not using multiple architectures.
I should get the same digest on '1.14.0' and '1.15.0'.

Any idea on what might cause this issue?

Thank you

### PR DESCRIPTION
**Pull request by fwininger**
resolve #88

### CODE REVIEW

**Comment by fwininger** [comment]
@deitch can you take a look ?

**Review by deitch — APPROVED** [review]

**Comment by yeikel** [comment]
I missed this. This header is not mandatory in the  spec and it won't be available in every registry implementation 

Do we have a solution for that?

**Comment by deitch** [comment]
Can you explain a bit further @yeikel ?

**Comment by yeikel** [comment]
> Can you explain a bit further @yeikel ?

As we discussed in https://github.com/deitch/docker_registry2/pull/85, this header is not always available in every Registry implementation and relying on it is unfortunate

**Comment by yeikel** [comment]
In particular this comment summarizes why we should not depend on this header https://github.com/deitch/docker_registry2/issues/83#issuecomment-1521034760

**Comment by yeikel** [comment]
I created https://github.com/deitch/docker_registry2/issues/98#issue-1891264232

**Pull request merged**
