### PR TITLE
Run integration tests with gh actions

### PR DESCRIPTION
**Pull request by vpereira**
The idea is to run the integration tests with docker-compose and automate it.

If you want to run it locally, you can start the docker-compose with `docker-compose up` and in another shell you can just call the script as usual with:

```
REGISTRY=http://localhost:5000  VERSION=v2 ruby ./test/test.rb
``` 

### BONUS:

I didn't remove your original scripts with this PR to avoid breaking any existing workflow. Instead i fixed it, so that now a `make test` will work. Moreover, you can use different image versions to enable the possibility to test with different ruby versions.

Happy hacking :rocket:

### CODE REVIEW

**Comment by deitch** [comment]
How does this relate to the changes already made in #70 ?

**Comment by deitch** [comment]
Sure, I am in favour of more testing, and more versions. `ci.yaml` already has [make build test](https://github.com/deitch/docker_registry2/blob/master/.github/workflows/ci.yaml#L32-L33). Is this intended to replace that? What is the overlap between the two?

**Comment by vpereira** [comment]
hi  @deitch i see.. i think this PR is improving the stack, making it ruby 3.1 and ruby 2.7 aware (if i read it correctly, today, its on ruby 2.4.x) and make test was breaking with newer dockers in the COPY command...

**Comment by deitch** [comment]
That looks solid, then. We just need to remove duplication between those two and we should be good to go.

**Comment by vpereira** [comment]
> That looks solid, then. We just need to remove duplication between those two and we should be good to go.

i will take care of that tomorrow 👍

**Comment by vpereira** [comment]
Hi @deitch I updated the PR. The checks look good https://github.com/deitch/docker_registry2/pull/71/checks running everything in parallel :+1:

**Review by deitch — APPROVED** [review]

**Pull request merged**
