### PR TITLE
Fix: add support for docker image manifest v2, schema 1 and 2

### PR DESCRIPTION
**Pull request by lehn-etracker**
Not all docker images are provided by schema v1 some use v2. The `pull`-method should recognize the correct schema and use correct REST endpoints to pull images.

This pull request will handle both.

### CODE REVIEW

**Comment by deitch** [comment]
This is really nice. When I wrote this, there really only was v1 (even in the v2 registry). I interacted with the docker people (now I work pretty closely with many of them and contribute to some of the projects), and I remember them saying that the default was going to be v2 "Real Soon Now".

I would like to test this with the various repos - should be easy to spin up a registry and test - and then will merge in.

**Comment by deitch** [comment]
Struggling with how to test it. Easiest method is to run a local latest version of the registry, put in 2 images (or one with 2 manifests), v1 and v2. 

The problem is pushing images. I can construct a bare `SCRATCH` image (or basic "hello world") easily. But any time you push an image to a v2 registry with docker >= 1.10, it automatically uses schema v2. 

Ideas on how to get it to give a v1 schema?

**Comment by deitch** [comment]
Thanks for this. I rolled it into https://github.com/deitch/docker_registry2/pull/20 and pushed out. Added your contribution to the CHANGELOG.

**Comment by lehn-etracker** [comment]
@deitch Thanks for merging. I've used https://www.sonatype.com/download-oss-sonatype as registry and have pushed one image with two tags. The first push used manifest v1 and second v2.

**Comment by deitch** [comment]
> I've used https://www.sonatype.com/download-oss-sonatype as registry and have pushed one image with two tags

Ah, that was smart. In the end, I just ran the docker registry 2.0.0, volume mounted storage, pushed, got v1, then stopped and started 2.6, same storage volume mount, pushed again with difference repo name, got v2. It is in the tests.

**Pull request closed without merging**
