### PR TITLE
Add multiarch images and manifests to our test environment

### PR DESCRIPTION
**Pull request by vpereira**
This PR still WIP, I'm adding support to work with multiarch images.

To create the "fixtures" to the test and development environment I did the following:

```
docker pull ubuntu:17.04
docker rmi ubuntu:17.04
docker push localhost:5000/my-ubuntu-arm64:17.04
docker pull --platform amd64 ubuntu:17.04
docker tag ubuntu:17.04 localhost:5000/my-ubuntu-amd64:17.04
docker rmi ubuntu:17.04
docker push localhost:5000/my-ubuntu-amd64:17.04
docker manifest create --insecure localhost:5000/my-ubuntu:17.04 localhost:5000/my-ubuntu-arm64:17.04 localhost:5000/my-ubuntu-amd64:17.04
docker manifest push --insecure localhost:5000/my-ubuntu:17.04
docker manifest inspect --insecure localhost:5000/my-ubuntu-amd64:17.04
docker manifest inspect --insecure localhost:5000/my-ubuntu:17.04
```

if you boot the docker environment with `docker-compose up` you can run the inspect commands as describe above.

if you want to try in the console:

```
$ irb
3.1.1 :002 > require_relative './lib/docker_registry2'
 => true 
3.1.1 :003 > d = DockerRegistry2.connect 'http://localhost:5000'
 => 
#<DockerRegistry2::Registry:0x00007fae5139da58
... 
3.1.1 :004 > m = d.manifest("my-ubuntu-arm64","17.04")
 => 
{"schemaVersion"=>2,
... 
3.1.1 :005 > m = d.manifest("my-ubuntu","17.04")
 => 
{"schemaVersion"=>2,
... 
3.1.1 :006 > m.fetch('manifests').map { |manifest| manifest.fetch('platform').fetch('architecture') }
 => ["amd64", "amd64"] 
```

TODO:

- [x] Add test images to local registry
- [x]  Adapt integration test to search for architectures
- [x] Add specs
- [ ] Implement the methods to work with images and architectures

### CODE REVIEW

**Comment by vpereira** [comment]
Hi @deitch could you add your two cents here in this PR?

I will add the specs to make sure we avoid any future regression, but i think it's feature complete.

**Comment by vpereira** [comment]
> I rather like how you did the tests, but can we drop the "fat manifest" terminology? I have never heard it used before here, always was manifest and multi-arch manifest, or manifest and distribution list (for docker), and manifest and index (for OCI).

I updated the test to reflect that.  Again I didn't coin this term, that's from the official documentation https://docs.docker.com/registry/spec/manifest-v2-2/ 

"_... the first is to allow multi-architecture images, through a “fat manifest” which references image manifests for platform-specific versions of an image. .._"

**Comment by deitch** [comment]
Yeah, I know it is in the docs, but I hear no one using that term, so I prefer to avoid it.

Is this ready to go?

**Comment by vpereira** [comment]
Hi @deitch, yes its ready to go!

**Review by deitch — APPROVED** [review]

**Comment by deitch** [comment]
Looking great! Thank you.

**Pull request merged**
