### PR TITLE
Adding reg.blob to fetch blobs according to v2 api

### PR DESCRIPTION
**Pull request by thomasf1234**
I've manually tested that this works as I'm currently using this in another project. Have added to the unit tests but couldn't get the tests to run as I faced issues with alpine unable to resolve DNS (Running locally on Ubuntu 18.04.3 VM). 

@deitch If you're satisfied with these changes can you please run the tests to verify they still pass with these additions? The tests are failing in CircleCI unrelated because of licensing.

### CODE REVIEW

**Comment by deitch** [comment]
Hi @thomasf1234 . Thanks for this PR; I always am happy to see the functionality expanded and greater spec compliance. I also appreciate the immediate attention to the `README.me`; not everyone assumes someone might actually want to learn how to use the new feature. :-)

I have two questions.

First, the body.  The body for a layer can be quite large, which is why, e.g. `pull()` pulls an entire image down to a directory. Would it not make sense to do the same here, i.e. deposit the body in a file somewhere, or at the very least do so by default with an in-memory option? If someone wants to download a 4GB blob to memory and blow up their laptop/VM, that is their business, but at least not face it upon them?

Second, I got a parser error when using it on layer blobs. See the following:

```ruby
> reg = DockerRegistry2.connect("https://registry.hub.docker.com")
> reg.manifest "library/nginx", "1.17.6-alpine"
 => {"schemaVersion"=>2, "mediaType"=>"application/vnd.docker.distribution.manifest.v2+json", "config"=>{"mediaType"=>"application/vnd.docker.container.image.v1+json", "size"=>7016, "digest"=>"sha256:a624d888d69ffdc185ed3b9c9c0645e8eaaac843ce59e89f1fbe45b0581e4ef6"}, "layers"=>[{"mediaType"=>"application/vnd.docker.image.rootfs.diff.tar.gzip", "size"=>2787134, "digest"=>"sha256:89d9c30c1d48bac627e5c6cb0d1ed1eec28e7dbdfbcc04712e4c79c0f83faf17"}, {"mediaType"=>"application/vnd.docker.image.rootfs.diff.tar.gzip", "size"=>5984561, "digest"=>"sha256:24f1c4f0b2f40c236ec9c306bd841778f30db9e6e7f067512732147ae7c11b07"}]}
> # makes sense, e.g. let us get the config
> foo = reg.blob "library/nginx", "sha256:a624d888d69ffdc185ed3b9c9c0645e8eaaac843ce59e89f1fbe45b0581e4ef6"
 => {"architecture"=>"amd64", "config"=>{"Hostname"=>"", "Domainname"=>"", "User"=>"", "AttachStdin"=>false, "AttachStdout"=>false, "AttachStderr"=>false, "ExposedPorts"=>{"80/tcp"=>{}}, "Tty"=>false, "OpenStdin"=>false, "StdinOnce"=>false, "Env"=>["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "NGINX_VERSION=1.17.6", "NJS_VERSION=0.3.7", "PKG_RELEASE=1"], "Cmd"=>["nginx", "-g", "daemon off;"], "ArgsEscaped"=>true, "Image"=>"sha256:87fbbe5ed7a499baa6603cd81502cfe0f26d0e9fe8b2feca8bc4ab04cd87c01e", "Volumes"=>nil, "WorkingDir"=>"", "Entrypoint"=>nil, "OnBuild"=>nil, "Labels"=>{"maintainer"=>"NGINX Docker Maintainers <docker-maint@nginx.com>"}, "StopSignal"=>"SIGTERM"}, "container"=>"07fd83ec50fc17566cdc75da347bee698c6910182d3498faa14ed83c00578a01", "container_config"=>{"Hostname"=>"07fd83ec50fc", "Domainname"=>"", "User"=>"", "AttachStdin"=>false, "AttachStdout"=>false, "AttachStderr"=>false, "ExposedPorts"=>{"80/tcp"=>{}}, "Tty"=>false, "OpenStdin"=>false, "StdinOnce"=>false, "Env"=>["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "NGINX_VERSION=1.17.6", "NJS_VERSION=0.3.7", "PKG_RELEASE=1"], "Cmd"=>["/bin/sh", "-c", "#(nop) ", "CMD [\"nginx\" \"-g\" \"daemon off;\"]"], "ArgsEscaped"=>true, "Image"=>"sha256:87fbbe5ed7a499baa6603cd81502cfe0f26d0e9fe8b2feca8bc4ab04cd87c01e", "Volumes"=>nil, "WorkingDir"=>"", "Entrypoint"=>nil, "OnBuild"=>nil, "Labels"=>{"maintainer"=>"NGINX Docker Maintainers <docker-maint@nginx.com>"}, "StopSignal"=>"SIGTERM"}, "created"=>"2019-11-20T01:16:50.939316846Z", "docker_version"=>"18.06.1-ce", "history"=>[{"created"=>"2019-10-21T17:21:42.078618181Z", "created_by"=>"/bin/sh -c #(nop) ADD file:fe1f09249227e2da2089afb4d07e16cbf832eeb804120074acd2b8192876cd28 in / "}, {"created"=>"2019-10-21T17:21:42.387111039Z", "created_by"=>"/bin/sh -c #(nop)  CMD [\"/bin/sh\"]", "empty_layer"=>true}, {"created"=>"2019-10-21T19:02:07.778861981Z", "created_by"=>"/bin/sh -c #(nop)  LABEL maintainer=NGINX Docker Maintainers <docker-maint@nginx.com>", "empty_layer"=>true}, {"created"=>"2019-11-20T01:16:43.082788948Z", "created_by"=>"/bin/sh -c #(nop)  ENV NGINX_VERSION=1.17.6", "empty_layer"=>true}, {"created"=>"2019-11-20T01:16:43.342750497Z", "created_by"=>"/bin/sh -c #(nop)  ENV NJS_VERSION=0.3.7", "empty_layer"=>true}, {"created"=>"2019-11-20T01:16:43.645677566Z", "created_by"=>"/bin/sh -c #(nop)  ENV PKG_RELEASE=1", "empty_layer"=>true}, {"created"=>"2019-11-20T01:16:50.080716088Z", "created_by"=>"/bin/sh -c set -x     && addgroup -g 101 -S nginx     && adduser -S -D -H -u 101 -h /var/cache/nginx -s /sbin/nologin -G nginx -g nginx nginx     && apkArch=\"$(cat /etc/apk/arch)\"     && nginxPackages=\"         nginx=${NGINX_VERSION}-r${PKG_RELEASE}         nginx-module-xslt=${NGINX_VERSION}-r${PKG_RELEASE}         nginx-module-geoip=${NGINX_VERSION}-r${PKG_RELEASE}         nginx-module-image-filter=${NGINX_VERSION}-r${PKG_RELEASE}         nginx-module-njs=${NGINX_VERSION}.${NJS_VERSION}-r${PKG_RELEASE}     \"     && case \"$apkArch\" in         x86_64)             set -x             && KEY_SHA512=\"e7fa8303923d9b95db37a77ad46c68fd4755ff935d0a534d26eba83de193c76166c68bfe7f65471bf8881004ef4aa6df3e34689c305662750c0172fca5d8552a *stdin\"             && apk add --no-cache --virtual .cert-deps                 openssl             && wget -O /tmp/nginx_signing.rsa.pub https://nginx.org/keys/nginx_signing.rsa.pub             && if [ \"$(openssl rsa -pubin -in /tmp/nginx_signing.rsa.pub -text -noout | openssl sha512 -r)\" = \"$KEY_SHA512\" ]; then                 echo \"key verification succeeded!\";                 mv /tmp/nginx_signing.rsa.pub /etc/apk/keys/;             else                 echo \"key verification failed!\";                 exit 1;             fi             && apk del .cert-deps             && apk add -X \"https://nginx.org/packages/mainline/alpine/v$(egrep -o '^[0-9]+\\.[0-9]+' /etc/alpine-release)/main\" --no-cache $nginxPackages             ;;         *)             set -x             && tempDir=\"$(mktemp -d)\"             && chown nobody:nobody $tempDir             && apk add --no-cache --virtual .build-deps                 gcc                 libc-dev                 make                 openssl-dev                 pcre-dev                 zlib-dev                 linux-headers                 libxslt-dev                 gd-dev                 geoip-dev                 perl-dev                 libedit-dev                 mercurial                 bash                 alpine-sdk                 findutils             && su nobody -s /bin/sh -c \"                 export HOME=${tempDir}                 && cd ${tempDir}                 && hg clone https://hg.nginx.org/pkg-oss                 && cd pkg-oss                 && hg up ${NGINX_VERSION}-${PKG_RELEASE}                 && cd alpine                 && make all                 && apk index -o ${tempDir}/packages/alpine/${apkArch}/APKINDEX.tar.gz ${tempDir}/packages/alpine/${apkArch}/*.apk                 && abuild-sign -k ${tempDir}/.abuild/abuild-key.rsa ${tempDir}/packages/alpine/${apkArch}/APKINDEX.tar.gz                 \"             && cp ${tempDir}/.abuild/abuild-key.rsa.pub /etc/apk/keys/             && apk del .build-deps             && apk add -X ${tempDir}/packages/alpine/ --no-cache $nginxPackages             ;;     esac     && if [ -n \"$tempDir\" ]; then rm -rf \"$tempDir\"; fi     && if [ -n \"/etc/apk/keys/abuild-key.rsa.pub\" ]; then rm -f /etc/apk/keys/abuild-key.rsa.pub; fi     && if [ -n \"/etc/apk/keys/nginx_signing.rsa.pub\" ]; then rm -f /etc/apk/keys/nginx_signing.rsa.pub; fi     && apk add --no-cache --virtual .gettext gettext     && mv /usr/bin/envsubst /tmp/         && runDeps=\"$(         scanelf --needed --nobanner /tmp/envsubst             | awk '{ gsub(/,/, \"\\nso:\", $2); print \"so:\" $2 }'             | sort -u             | xargs -r apk info --installed             | sort -u     )\"     && apk add --no-cache $runDeps     && apk del .gettext     && mv /tmp/envsubst /usr/local/bin/     && apk add --no-cache tzdata     && ln -sf /dev/stdout /var/log/nginx/access.log     && ln -sf /dev/stderr /var/log/nginx/error.log"}, {"created"=>"2019-11-20T01:16:50.458530898Z", "created_by"=>"/bin/sh -c #(nop)  EXPOSE 80", "empty_layer"=>true}, {"created"=>"2019-11-20T01:16:50.690704775Z", "created_by"=>"/bin/sh -c #(nop)  STOPSIGNAL SIGTERM", "empty_layer"=>true}, {"created"=>"2019-11-20T01:16:50.939316846Z", "created_by"=>"/bin/sh -c #(nop)  CMD [\"nginx\" \"-g\" \"daemon off;\"]", "empty_layer"=>true}], "os"=>"linux", "rootfs"=>{"type"=>"layers", "diff_ids"=>["sha256:77cae8ab23bf486355d1b3191259705374f4a11d483b24964d2f729dd8c076a0", "sha256:f4cef7054e837eb301d4c669bf2b58b3f764188d4a8e20dd65fcbfa4d7f688a1"]}}
> # now try to get a layer
> foo = reg.blob "library/nginx", "sha256:24f1c4f0b2f40c236ec9c306bd841778f30db9e6e7f067512732147ae7c11b07"
JSON::ParserError: 757: unexpected token at ''
	from /Users/adeitcher/.rvm/gems/ruby-2.2.5/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
	from /Users/adeitcher/.rvm/gems/ruby-2.2.5/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
	from /Users/adeitcher/Documents/Development/docker/registry_gem/lib/registry/registry.rb:112:in `blob'
	from (irb):36
	from /Users/adeitcher/.rvm/rubies/ruby-2.2.5/bin/irb:11:in `<main>'
```

I suspect this is because it is [parsing the blob](https://github.com/deitch/docker_registry2/pull/43/files#diff-903778ca60f39c460a3f2e75956d84ffR111), always expecting it to be a json, which is not true. It is just a blob, which might be binary data, might be json, might be something else entirely.

**Comment by deitch** [comment]
Also please rebase off of master. I replaced circle with actions.

**Comment by thomasf1234** [comment]
@deitch : Appreciate such in depth feedback and review. Firstly I apologise that I had not read the API in depth yesterday and had mistakenly misread the blob api was for image blobs (and hence json). I am in full agreement with the points you have made and so have updated the blob method with the option you have suggested which gives full control to the user, and removes any false assumption of the blob content. Thank you for pointing this out to me.

I have also made a minor refactor within the pull image methods to utilise this new method. I would normally run these tests locally before committing/pushing but because of the aforementioned issues I haven't, so I hope you don't mind the noise in the commit history.

Do these changes satisfy what you had in mind?

**Comment by deitch** [comment]
No apologies necessary. I appreciate your contribution. It’s all an iterative learning experience for all of us (don’t ask why I spent time wondering what was broken with your proposal before I realized that I was using the wrong hashes 😂 ). 

It looks good and CI passes. I’ll take a look when I’m back on laptop and get it merged in.

**Comment by thomasf1234** [comment]
Thank you, aha well as soon as you mentioned about layers it clicked in my head and realised it needed completely changing!

**Comment by deitch** [comment]
Looks good. Thanks for adding it in!

**Comment by deitch** [comment]
Drat. I merged, and didn't bump the version, which will cause a deploy fail. I realized the second after I git "merge". I will fix that.

**Comment by thomasf1234** [comment]
Ah brilliant thank you for that.

**Pull request merged**
