### PR TITLE
Follow the pagination in the repositories listing

### PR DESCRIPTION
**Pull request by fmang**
Registry#search only fetched the first page, even though the API specification
states that the catalog route can be paginated. Let’s fetch all the pages
instead.

The function prototype was kept simplistic, unlike Registry#tag which provides
finer controls but is much harder to use. The rationale is that most users
expect the full list and do not have to be aware of the pagination details of
the API. If the eager loading causes issues, we could return a lazy Enumerator.

### CODE REVIEW

**Comment by fwininger** [comment]
thanks, can you merge this @deitch ?

**Review by deitch — APPROVED** [review]
Nicely done. Thank you for expanding the capabilities.

**Comment by fwininger** [comment]
@deitch can you release a new version with this ?

**Comment by deitch** [comment]
Done. Should take a few minutes to run through.

**Comment by fwininger** [comment]
Thanks ;)

**Pull request merged**
