### PR TITLE
Automatically paginate tags response if auto_paginate param is passed

### PR DESCRIPTION
**Pull request by greysteil**
Adds an `auto_paginate` argument to the `tags` endpoint, and automatically paginate through all tags if set to true.

This is what we'll want to do in Dependabot, and I imagine others will want the same.

Tested locally which is the best we can do here without adding pagination headers to the mocked registry.

### CODE REVIEW

**Comment by deitch** [comment]
Nice @greysteil ! Can you please rebase off `master`? I finally got circleci working correctly...

**Comment by greysteil** [comment]
Done but looks like it's not building - have you got CI set to build on PRs from forks?

**Comment by deitch** [comment]
Oops, it was not. Changed now.

**Comment by greysteil** [comment]
💚

**Comment by deitch** [comment]
That worked.

**Comment by deitch** [comment]
Uh oh, I didn't check that you bumped the minor version number. Shoot. Better open a new PR for it?

**Pull request merged**
