### PR TITLE
Restore exceptions inheriting from parent class

### PR DESCRIPTION
**Pull request by zarqman**
ee6598b accidentally changed the parent class of all exceptions from `DockerRegistry2::Exception` to `::StandardError`. This PR restores the previous parent class and includes its module name so rubocop doesn't complain and re-recommend `StandardError`.

This is needed so dependent code can once again rescue all possible DockerRegistry2 exceptions.

### CODE REVIEW

**Comment by deitch** [comment]
@vpereira made that PR change referenced; Victor, do you mind commenting here? Any issues?

**Comment by zarqman** [comment]
Thought I'd touch base and see if there are any concerns or other feedback on this PR?

**Comment by vpereira** [comment]
Hi @deitch and @zarqman!

Looks like those changes were done by rubocop. To revert it kind of make sense, the only thing that I would ask here is:

Rubocop changed it probably because of https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/InheritException

a) Do we need a custom base exception named `Exception` ? Looks like rubocop can be configured to use `RuntimeError`, which then IMO would behave exactly as before without one layer of abstraction. I'm fine as well with have a custom base exception

b) Add it to the rubocop list (i.e re-generate the TODO) to avoid having it being corrected again in the near future

**Comment by zarqman** [comment]
@vpereira, per your suggestion, I just ran `rubycop --regenerate-todo` and `rubycop -A` on my local branch and it only updated the `.rubocop_todo.yml` file, not any of the code. I believe that confirms that rubocop will not accidentally reintroduce this regression in the future.

I agree that rubocop likely made the change based on its `InheritException` rule. My read of its comments (thanks for including the link!) suggests that configuring it is about it's suggested remedy, and not about how it parses things to begin with.

However, the original problem is that rubocop appears to have a parsing bug in that it incorrectly identified the original base exception as if it were `::Exception` instead of `DockerRegistry2::Exception`, despite the latter being what it really was. Put another way, rubocop failed to recognize the implied module name on the in-module base class.

Thus, I don't believe configuring rubocop/InheritException would help, as it doesn't address rubocop's failure to correctly parse things to begin with.

I considered renaming the base exception to `DockerRegistry2::Error` (since that would sidestep rubocop's parsing issue), but that's a breaking change and the [readme](https://github.com/deitch/docker_registry2#exceptions) expressly calls out the existing base exception class name. Since both a rename and adding the full module name are viable fixes, I chose to go with the latter as it's non-breaking.

**Review by vpereira — APPROVED** [review]
@deitch  @zarqman alright, thank you for your analysis!

Avi, thank you for letting me know. From my side the PR is approved.

Just to be a good open source citizen, I opened an issue to rubocop: https://github.com/rubocop/rubocop/issues/11893

Happy hacking!

**Review by vpereira — APPROVED** [review]

**Comment by vpereira** [comment]
> @vpereira, per your suggestion, I just ran `rubycop --regenerate-todo` and `rubycop -A` on my local branch and it only updated the `.rubocop_todo.yml` file, not any of the code. I believe that confirms that rubocop will not accidentally reintroduce this regression in the future.

It updated the `rubocop_todo.yml` and then running the `rubocop -A` didn't change any code. But then you should commit the new `.rubocop_todo.yml` to your PR no @zarqman ?

**Comment by zarqman** [comment]
@vpereira Added!

**Review by deitch — APPROVED** [review]

**Comment by deitch** [comment]
Ci is running, and it was approved, so just wait for CI to be green and in it goes.

**Comment by deitch** [comment]
Why is rubocop upset?

**Comment by zarqman** [comment]
At first glance, at least some of rubocop's complaints seem to be line length concerns coming from the recently committed #85. That PR didn't flag rubocop errors though, so I'm guessing it's a combo of that plus the `rubycop --regenerate-todo` that was requested here.

Fixing those errors seems out of scope on this PR, so I'll propose to unwind the 'regenerate rubocop_todo' commit here. However, I'll wait a day or so to allow either of you to weigh in on whether that's the best path.

**Comment by deitch** [comment]
Works for me.

**Comment by zarqman** [comment]
I ended up rebasing this PR against 1.15.0 (was against 1.14.0 previously) and then re-ran rubocop regenerate again.

Merely rebasing and reverting the prior regenerate resulted in a different set of errors than in the prior workflow check. And, I'm not sure what's causing all this variance, nor do I understand why rubocop successfully passed on recent PRs but seems to be complaining now.

It might be a rubocop (or dependency) versioning issue, in which case committing Gemfile.lock or locking the rubocop version more tightly might help.

Everything passes locally, but let's see what the workflow checks do and go from there.

**Comment by vpereira** [comment]
Congrats @zarqman you improved `docker_registry` and `rubocop` in one PR: https://github.com/rubocop/rubocop/issues/11893 thank you :rocket:

**Comment by vpereira** [comment]
@deitch looks like you have to approve the workflow run?

**Pull request merged**
